const SEED_DATA = {
  "accounts": [
    {
      "id": "a1",
      "name": "IOB Salary",
      "openingBalance": 16019,
      "openingDate": "2026-08-10",
      "purpose": "Salary receipt",
      "status": "Active"
    },
    {
      "id": "a2",
      "name": "IOB Personal",
      "openingBalance": 2.29,
      "openingDate": "2026-08-10",
      "purpose": "Emergency fund",
      "status": "Active"
    },
    {
      "id": "a3",
      "name": "SBI",
      "openingBalance": 10341.11,
      "openingDate": "2026-08-10",
      "purpose": "Regular expenses",
      "status": "Active"
    },
    {
      "id": "a4",
      "name": "Physical Cash",
      "openingBalance": 0,
      "openingDate": "2026-08-10",
      "purpose": "Petty cash",
      "status": "Active"
    }
  ],
  "transactions": [
    {
      "id": "t1",
      "date": "2026-08-10",
      "amount": 4287,
      "source": "SBI",
      "dest": null,
      "type": "Debt repayment",
      "category": "Debt & Loans",
      "subcategory": "Debt repaid by me",
      "description": "Latheef shop",
      "paymentMethod": "SBI account / UPI",
      "person": null,
      "notes": ""
    },
    {
      "id": "t2",
      "date": "2026-08-11",
      "amount": 120,
      "source": "SBI",
      "dest": null,
      "type": "Expense",
      "category": "Vehicle",
      "subcategory": "Petrol/Fuel",
      "description": "Petrol",
      "paymentMethod": "SBI account / UPI",
      "person": null,
      "notes": ""
    },
    {
      "id": "t3",
      "date": "2026-08-11",
      "amount": 30,
      "source": "SBI",
      "dest": null,
      "type": "Expense",
      "category": "Food",
      "subcategory": "Snacks",
      "description": "Tea",
      "paymentMethod": "SBI account / UPI",
      "person": null,
      "notes": ""
    },
    {
      "id": "t4",
      "date": "2026-08-11",
      "amount": 230,
      "source": "SBI",
      "dest": null,
      "type": "Expense",
      "category": "Work Related",
      "subcategory": "Work tools/equipment",
      "description": "Laser tape battery",
      "paymentMethod": "SBI account / UPI",
      "person": null,
      "notes": ""
    },
    {
      "id": "t5",
      "date": "2026-08-11",
      "amount": 60,
      "source": "SBI",
      "dest": null,
      "type": "Expense",
      "category": "Food",
      "subcategory": "Other food",
      "description": "Lime",
      "paymentMethod": "SBI account / UPI",
      "person": null,
      "notes": ""
    },
    {
      "id": "t6",
      "date": "2026-08-11",
      "amount": 20,
      "source": "SBI",
      "dest": null,
      "type": "Refund/Reimbursement",
      "category": "Food",
      "subcategory": "Other food",
      "description": "Adarsh lime return",
      "paymentMethod": "SBI account / UPI",
      "person": null,
      "notes": ""
    },
    {
      "id": "t7",
      "date": "2026-08-11",
      "amount": 20,
      "source": "SBI",
      "dest": null,
      "type": "Refund/Reimbursement",
      "category": "Food",
      "subcategory": "Other food",
      "description": "Jayesh lime return",
      "paymentMethod": "SBI account / UPI",
      "person": null,
      "notes": ""
    },
    {
      "id": "t8",
      "date": "2026-08-11",
      "amount": 120,
      "source": "SBI",
      "dest": null,
      "type": "Expense",
      "category": "Vehicle",
      "subcategory": "Petrol/Fuel",
      "description": "Petrol",
      "paymentMethod": "SBI account / UPI",
      "person": null,
      "notes": ""
    },
    {
      "id": "t9",
      "date": "2026-08-11",
      "amount": 24,
      "source": "SBI",
      "dest": null,
      "type": "Expense",
      "category": "Food",
      "subcategory": "Snacks",
      "description": "Tea",
      "paymentMethod": "SBI account / UPI",
      "person": null,
      "notes": ""
    },
    {
      "id": "t10",
      "date": "2026-08-11",
      "amount": 344,
      "source": "SBI",
      "dest": null,
      "type": "Expense",
      "category": "Housing & Household",
      "subcategory": "Groceries",
      "description": "Peanut butter & milk",
      "paymentMethod": "SBI account / UPI",
      "person": null,
      "notes": ""
    },
    {
      "id": "t11",
      "date": "2026-08-12",
      "amount": 608,
      "source": "SBI",
      "dest": null,
      "type": "Expense",
      "category": "Housing & Household",
      "subcategory": "Water",
      "description": "Water bill",
      "paymentMethod": "SBI account / UPI",
      "person": null,
      "notes": ""
    },
    {
      "id": "t12",
      "date": "2026-08-12",
      "amount": 120,
      "source": "SBI",
      "dest": null,
      "type": "Expense",
      "category": "Vehicle",
      "subcategory": "Petrol/Fuel",
      "description": "Petrol",
      "paymentMethod": "SBI account / UPI",
      "person": null,
      "notes": ""
    },
    {
      "id": "t13",
      "date": "2026-08-12",
      "amount": 90,
      "source": "SBI",
      "dest": null,
      "type": "Expense",
      "category": "Work Related",
      "subcategory": "Work tools/equipment",
      "description": "Hilti bit",
      "paymentMethod": "SBI account / UPI",
      "person": null,
      "notes": ""
    },
    {
      "id": "t14",
      "date": "2026-08-12",
      "amount": 179,
      "source": "SBI",
      "dest": null,
      "type": "Expense",
      "category": "Food",
      "subcategory": "Eating out",
      "description": "Lunch",
      "paymentMethod": "SBI account / UPI",
      "person": null,
      "notes": ""
    },
    {
      "id": "t15",
      "date": "2026-08-12",
      "amount": 35,
      "source": "SBI",
      "dest": null,
      "type": "Expense",
      "category": "Food",
      "subcategory": "Snacks",
      "description": "Tea",
      "paymentMethod": "SBI account / UPI",
      "person": null,
      "notes": ""
    },
    {
      "id": "t16",
      "date": "2026-08-12",
      "amount": 440,
      "source": "SBI",
      "dest": null,
      "type": "Expense",
      "category": "Housing & Household",
      "subcategory": "Groceries",
      "description": "Egg",
      "paymentMethod": "SBI account / UPI",
      "person": null,
      "notes": ""
    },
    {
      "id": "t17",
      "date": "2026-08-12",
      "amount": 80,
      "source": "SBI",
      "dest": null,
      "type": "Expense",
      "category": "Work Related",
      "subcategory": "Work tools/equipment",
      "description": "Hilti bit- Adarsh",
      "paymentMethod": "SBI account / UPI",
      "person": null,
      "notes": ""
    },
    {
      "id": "t18",
      "date": "2026-08-12",
      "amount": 3000,
      "source": "SBI",
      "dest": "Physical Cash",
      "type": "Transfer",
      "category": null,
      "subcategory": null,
      "description": "Cash withdrawn",
      "paymentMethod": null,
      "person": null,
      "notes": ""
    },
    {
      "id": "t19",
      "date": "2026-08-12",
      "amount": 3000,
      "source": "Physical Cash",
      "dest": null,
      "type": "Expense",
      "category": "Family",
      "subcategory": "Family support",
      "description": "Umma expense",
      "paymentMethod": "Physical cash",
      "person": null,
      "notes": ""
    },
    {
      "id": "t20",
      "date": "2026-08-12",
      "amount": 120,
      "source": "SBI",
      "dest": null,
      "type": "Expense",
      "category": "Vehicle",
      "subcategory": "Petrol/Fuel",
      "description": "Petrol",
      "paymentMethod": "SBI account / UPI",
      "person": null,
      "notes": ""
    },
    {
      "id": "t21",
      "date": "2026-08-12",
      "amount": 276,
      "source": "SBI",
      "dest": null,
      "type": "Debt repayment",
      "category": "Debt & Loans",
      "subcategory": "Debt repaid by me",
      "description": "Amazon Pay-later repayment",
      "paymentMethod": "SBI account / UPI",
      "person": null,
      "notes": ""
    },
    {
      "id": "t22",
      "date": "2026-08-12",
      "amount": 10000,
      "source": "IOB Salary",
      "dest": "SBI",
      "type": "Transfer",
      "category": null,
      "subcategory": null,
      "description": "Expense transfer",
      "paymentMethod": null,
      "person": null,
      "notes": ""
    },
    {
      "id": "t23",
      "date": "2026-08-12",
      "amount": 150,
      "source": "SBI",
      "dest": null,
      "type": "Expense",
      "category": "Personal",
      "subcategory": "Other personal",
      "description": "Achu exam fee",
      "paymentMethod": "SBI account / UPI",
      "person": null,
      "notes": ""
    },
    {
      "id": "t24",
      "date": "2026-08-12",
      "amount": 1000,
      "source": "SBI",
      "dest": null,
      "type": "Money Lent",
      "category": null,
      "subcategory": null,
      "description": "Haris lent",
      "paymentMethod": "SBI account / UPI",
      "person": "Haris",
      "notes": ""
    },
    {
      "id": "t25",
      "date": "2026-08-13",
      "amount": 120,
      "source": "SBI",
      "dest": null,
      "type": "Expense",
      "category": "Vehicle",
      "subcategory": "Petrol/Fuel",
      "description": "Petrol",
      "paymentMethod": "SBI account / UPI",
      "person": null,
      "notes": ""
    },
    {
      "id": "t26",
      "date": "2026-08-13",
      "amount": 2040,
      "source": "SBI",
      "dest": null,
      "type": "Expense",
      "category": "Work Related",
      "subcategory": "Reimbursable work expense",
      "description": "Techopark tender fee",
      "paymentMethod": "Debit card",
      "person": null,
      "notes": ""
    },
    {
      "id": "t27",
      "date": "2026-08-13",
      "amount": 14,
      "source": "SBI",
      "dest": null,
      "type": "Expense",
      "category": "Work Related",
      "subcategory": "Work materials",
      "description": "Tendor bid print",
      "paymentMethod": "SBI account / UPI",
      "person": null,
      "notes": ""
    },
    {
      "id": "t28",
      "date": "2026-08-13",
      "amount": 13,
      "source": "SBI",
      "dest": null,
      "type": "Expense",
      "category": "Work Related",
      "subcategory": "Work materials",
      "description": "Envelope & pen",
      "paymentMethod": "SBI account / UPI",
      "person": null,
      "notes": ""
    },
    {
      "id": "t29",
      "date": "2026-08-13",
      "amount": 70,
      "source": "SBI",
      "dest": null,
      "type": "Expense",
      "category": "Food",
      "subcategory": "Snacks",
      "description": "Chocolate",
      "paymentMethod": "SBI account / UPI",
      "person": null,
      "notes": ""
    },
    {
      "id": "t30",
      "date": "2026-08-13",
      "amount": 8,
      "source": "SBI",
      "dest": null,
      "type": "Expense",
      "category": "Personal",
      "subcategory": "Other personal",
      "description": "Pen",
      "paymentMethod": "SBI account / UPI",
      "person": null,
      "notes": ""
    },
    {
      "id": "t31",
      "date": "2026-08-13",
      "amount": 50,
      "source": "SBI",
      "dest": null,
      "type": "Refund/Reimbursement",
      "category": "Vehicle",
      "subcategory": "Petrol/Fuel",
      "description": "Gireesh Petrol",
      "paymentMethod": "SBI account / UPI",
      "person": null,
      "notes": ""
    },
    {
      "id": "t32",
      "date": "2026-08-13",
      "amount": 120,
      "source": "SBI",
      "dest": null,
      "type": "Expense",
      "category": "Vehicle",
      "subcategory": "Petrol/Fuel",
      "description": "Petrol",
      "paymentMethod": "SBI account / UPI",
      "person": null,
      "notes": ""
    },
    {
      "id": "t33",
      "date": "2026-08-13",
      "amount": 24,
      "source": "SBI",
      "dest": null,
      "type": "Expense",
      "category": "Food",
      "subcategory": "Snacks",
      "description": "Tea",
      "paymentMethod": "SBI account / UPI",
      "person": null,
      "notes": ""
    },
    {
      "id": "t34",
      "date": "2026-08-13",
      "amount": 20,
      "source": "SBI",
      "dest": null,
      "type": "Expense",
      "category": "Family",
      "subcategory": "Family support",
      "description": "Haris expense",
      "paymentMethod": "SBI account / UPI",
      "person": null,
      "notes": ""
    },
    {
      "id": "t35",
      "date": "2026-08-13",
      "amount": 24,
      "source": "SBI",
      "dest": null,
      "type": "Expense",
      "category": "Food",
      "subcategory": "Snacks",
      "description": "Tea",
      "paymentMethod": "SBI account / UPI",
      "person": null,
      "notes": ""
    },
    {
      "id": "t36",
      "date": "2026-08-13",
      "amount": 56,
      "source": "SBI",
      "dest": null,
      "type": "Expense",
      "category": "Housing & Household",
      "subcategory": "Groceries",
      "description": "Milk",
      "paymentMethod": "SBI account / UPI",
      "person": null,
      "notes": ""
    },
    {
      "id": "t37",
      "date": "2026-08-14",
      "amount": 2040,
      "source": "SBI",
      "dest": null,
      "type": "Refund/Reimbursement",
      "category": "Work Related",
      "subcategory": "Reimbursable work expense",
      "description": "JK Tender fee return",
      "paymentMethod": "SBI account / UPI",
      "person": null,
      "notes": ""
    },
    {
      "id": "t38",
      "date": "2026-08-14",
      "amount": 18,
      "source": "SBI",
      "dest": null,
      "type": "Expense",
      "category": "Food",
      "subcategory": "Snacks",
      "description": "Meatroll",
      "paymentMethod": "SBI account / UPI",
      "person": null,
      "notes": ""
    },
    {
      "id": "t39",
      "date": "2026-08-14",
      "amount": 220,
      "source": "SBI",
      "dest": null,
      "type": "Expense",
      "category": "Vehicle",
      "subcategory": "Petrol/Fuel",
      "description": "Petrol",
      "paymentMethod": "SBI account / UPI",
      "person": null,
      "notes": ""
    },
    {
      "id": "t40",
      "date": "2026-08-14",
      "amount": 10,
      "source": "SBI",
      "dest": null,
      "type": "Expense",
      "category": "Food",
      "subcategory": "Snacks",
      "description": "Tea",
      "paymentMethod": "SBI account / UPI",
      "person": null,
      "notes": ""
    },
    {
      "id": "t41",
      "date": "2026-08-14",
      "amount": 100,
      "source": "SBI",
      "dest": null,
      "type": "Expense",
      "category": "Housing & Household",
      "subcategory": "Groceries",
      "description": "Chappathi",
      "paymentMethod": "SBI account / UPI",
      "person": null,
      "notes": ""
    },
    {
      "id": "t42",
      "date": "2026-08-15",
      "amount": 120,
      "source": "SBI",
      "dest": null,
      "type": "Expense",
      "category": "Vehicle",
      "subcategory": "Petrol/Fuel",
      "description": "Petrol",
      "paymentMethod": "SBI account / UPI",
      "person": null,
      "notes": ""
    },
    {
      "id": "t43",
      "date": "2026-08-15",
      "amount": 80,
      "source": "SBI",
      "dest": null,
      "type": "Expense",
      "category": "Work Related",
      "subcategory": "Work tools/equipment",
      "description": "Tile core bit",
      "paymentMethod": "SBI account / UPI",
      "person": null,
      "notes": ""
    },
    {
      "id": "t44",
      "date": "2026-08-15",
      "amount": 500,
      "source": "SBI",
      "dest": null,
      "type": "Expense",
      "category": "Work Related",
      "subcategory": "Pickup fuel",
      "description": "Blife pickup diesel",
      "paymentMethod": "SBI account / UPI",
      "person": null,
      "notes": ""
    },
    {
      "id": "t45",
      "date": "2026-08-15",
      "amount": 24,
      "source": "SBI",
      "dest": null,
      "type": "Expense",
      "category": "Food",
      "subcategory": "Snacks",
      "description": "Tea",
      "paymentMethod": "SBI account / UPI",
      "person": null,
      "notes": ""
    },
    {
      "id": "t46",
      "date": "2026-08-15",
      "amount": 75,
      "source": "SBI",
      "dest": null,
      "type": "Expense",
      "category": "Family",
      "subcategory": "Family support",
      "description": "Anees expense",
      "paymentMethod": "SBI account / UPI",
      "person": null,
      "notes": ""
    },
    {
      "id": "t47",
      "date": "2026-08-16",
      "amount": 2500,
      "source": "IOB Salary",
      "dest": "SBI",
      "type": "Transfer",
      "category": null,
      "subcategory": null,
      "description": "Cash transfer",
      "paymentMethod": null,
      "person": null,
      "notes": ""
    },
    {
      "id": "t48",
      "date": "2026-08-16",
      "amount": 8000,
      "source": "SBI",
      "dest": null,
      "type": "Expense",
      "category": "Housing & Household",
      "subcategory": "Rent",
      "description": "August rent",
      "paymentMethod": "SBI account / UPI",
      "person": null,
      "notes": ""
    },
    {
      "id": "t49",
      "date": "2026-08-16",
      "amount": 30,
      "source": "SBI",
      "dest": null,
      "type": "Expense",
      "category": "Family",
      "subcategory": "Family support",
      "description": "Haris expense",
      "paymentMethod": "SBI account / UPI",
      "person": null,
      "notes": ""
    },
    {
      "id": "t50",
      "date": "2026-08-16",
      "amount": 150,
      "source": "SBI",
      "dest": null,
      "type": "Expense",
      "category": "Family",
      "subcategory": "Family support",
      "description": "Anees expense",
      "paymentMethod": "SBI account / UPI",
      "person": null,
      "notes": ""
    },
    {
      "id": "t51",
      "date": "2026-08-17",
      "amount": 80,
      "source": "SBI",
      "dest": null,
      "type": "Expense",
      "category": "Family",
      "subcategory": "Family medical",
      "description": "Umma sugar test",
      "paymentMethod": "SBI account / UPI",
      "person": null,
      "notes": ""
    },
    {
      "id": "t52",
      "date": "2026-08-17",
      "amount": 24,
      "source": "SBI",
      "dest": null,
      "type": "Expense",
      "category": "Food",
      "subcategory": "Snacks",
      "description": "Tea",
      "paymentMethod": "SBI account / UPI",
      "person": null,
      "notes": ""
    },
    {
      "id": "t53",
      "date": "2026-08-17",
      "amount": 160,
      "source": "SBI",
      "dest": null,
      "type": "Expense",
      "category": "Food",
      "subcategory": "Eating out",
      "description": "Lunch",
      "paymentMethod": "SBI account / UPI",
      "person": null,
      "notes": ""
    },
    {
      "id": "t54",
      "date": "2026-08-17",
      "amount": 120,
      "source": "SBI",
      "dest": null,
      "type": "Expense",
      "category": "Vehicle",
      "subcategory": "Petrol/Fuel",
      "description": "Petrol",
      "paymentMethod": "SBI account / UPI",
      "person": null,
      "notes": ""
    },
    {
      "id": "t55",
      "date": "2026-08-17",
      "amount": 100,
      "source": "SBI",
      "dest": null,
      "type": "Expense",
      "category": "Family",
      "subcategory": "Family support",
      "description": "Anees expense",
      "paymentMethod": "SBI account / UPI",
      "person": null,
      "notes": ""
    },
    {
      "id": "t56",
      "date": "2026-08-18",
      "amount": 10,
      "source": "SBI",
      "dest": null,
      "type": "Expense",
      "category": "Food",
      "subcategory": "Snacks",
      "description": "Tea",
      "paymentMethod": "SBI account / UPI",
      "person": null,
      "notes": ""
    },
    {
      "id": "t57",
      "date": "2026-08-18",
      "amount": 220,
      "source": "SBI",
      "dest": null,
      "type": "Expense",
      "category": "Family",
      "subcategory": "Family support",
      "description": "Haris expense",
      "paymentMethod": "SBI account / UPI",
      "person": null,
      "notes": ""
    },
    {
      "id": "t58",
      "date": "2026-08-18",
      "amount": 120,
      "source": "SBI",
      "dest": null,
      "type": "Expense",
      "category": "Vehicle",
      "subcategory": "Petrol/Fuel",
      "description": "Petrol",
      "paymentMethod": "SBI account / UPI",
      "person": null,
      "notes": ""
    },
    {
      "id": "t59",
      "date": "2026-08-18",
      "amount": 120,
      "source": "SBI",
      "dest": null,
      "type": "Expense",
      "category": "Vehicle",
      "subcategory": "Petrol/Fuel",
      "description": "Petrol",
      "paymentMethod": "SBI account / UPI",
      "person": null,
      "notes": ""
    },
    {
      "id": "t60",
      "date": "2026-08-18",
      "amount": 46,
      "source": "SBI",
      "dest": null,
      "type": "Expense",
      "category": "Food",
      "subcategory": "Snacks",
      "description": "Tea",
      "paymentMethod": "SBI account / UPI",
      "person": null,
      "notes": ""
    },
    {
      "id": "t61",
      "date": "2026-08-19",
      "amount": 120,
      "source": "SBI",
      "dest": null,
      "type": "Expense",
      "category": "Vehicle",
      "subcategory": "Petrol/Fuel",
      "description": "Petrol",
      "paymentMethod": "SBI account / UPI",
      "person": null,
      "notes": ""
    },
    {
      "id": "t62",
      "date": "2026-08-19",
      "amount": 24,
      "source": "SBI",
      "dest": null,
      "type": "Expense",
      "category": "Food",
      "subcategory": "Snacks",
      "description": "Tea",
      "paymentMethod": "SBI account / UPI",
      "person": null,
      "notes": ""
    },
    {
      "id": "t63",
      "date": "2026-08-19",
      "amount": 700,
      "source": "IOB Salary",
      "dest": "SBI",
      "type": "Transfer",
      "category": null,
      "subcategory": null,
      "description": "Cash transfer",
      "paymentMethod": null,
      "person": null,
      "notes": ""
    },
    {
      "id": "t64",
      "date": "2026-08-19",
      "amount": 1000,
      "source": "SBI",
      "dest": null,
      "type": "Expense",
      "category": "Vehicle",
      "subcategory": "Other vehicle expense",
      "description": "Vayalikkada accident compensation",
      "paymentMethod": "SBI account / UPI",
      "person": null,
      "notes": ""
    },
    {
      "id": "t65",
      "date": "2026-08-19",
      "amount": 19,
      "source": "SBI",
      "dest": null,
      "type": "Refund/Reimbursement",
      "category": "Other",
      "subcategory": null,
      "description": "Navi cashback",
      "paymentMethod": "SBI account / UPI",
      "person": null,
      "notes": ""
    },
    {
      "id": "t66",
      "date": "2026-08-19",
      "amount": 37.55,
      "source": "SBI",
      "dest": null,
      "type": "Refund/Reimbursement",
      "category": "Other",
      "subcategory": null,
      "description": "Supermoney cashback",
      "paymentMethod": "SBI account / UPI",
      "person": null,
      "notes": ""
    },
    {
      "id": "t67",
      "date": "2026-08-19",
      "amount": 45,
      "source": "SBI",
      "dest": null,
      "type": "Expense",
      "category": "Work Related",
      "subcategory": "Tools/equipments",
      "description": "iCloud Spanner",
      "paymentMethod": "SBI account / UPI",
      "person": null,
      "notes": ""
    },
    {
      "id": "t68",
      "date": "2026-08-19",
      "amount": 263.14,
      "source": "SBI",
      "dest": null,
      "type": "Expense",
      "category": "Work Related",
      "subcategory": "Travel expense",
      "description": "Thrissur train ticket",
      "paymentMethod": "SBI account / UPI",
      "person": null,
      "notes": ""
    },
    {
      "id": "t69",
      "date": "2026-08-19",
      "amount": 34,
      "source": "SBI",
      "dest": null,
      "type": "Expense",
      "category": "Food",
      "subcategory": "Snacks",
      "description": "Tea",
      "paymentMethod": "SBI account / UPI",
      "person": null,
      "notes": ""
    },
    {
      "id": "t70",
      "date": "2026-08-19",
      "amount": 500,
      "source": "IOB Salary",
      "dest": "SBI",
      "type": "Transfer",
      "category": null,
      "subcategory": null,
      "description": "Cash transfer",
      "paymentMethod": null,
      "person": null,
      "notes": ""
    },
    {
      "id": "t71",
      "date": "2026-08-19",
      "amount": 120,
      "source": "SBI",
      "dest": null,
      "type": "Expense",
      "category": "Vehicle",
      "subcategory": "Petrol/Fuel",
      "description": "Petrol",
      "paymentMethod": "SBI account / UPI",
      "person": null,
      "notes": ""
    },
    {
      "id": "t72",
      "date": "2026-08-20",
      "amount": 25,
      "source": "SBI",
      "dest": null,
      "type": "Expense",
      "category": "Food",
      "subcategory": "Snacks",
      "description": "Tea & water",
      "paymentMethod": "SBI account / UPI",
      "person": null,
      "notes": ""
    },
    {
      "id": "t73",
      "date": "2026-08-20",
      "amount": 1000,
      "source": "SBI",
      "dest": null,
      "type": "Refund/Reimbursement",
      "category": null,
      "subcategory": null,
      "description": "Accident refund",
      "paymentMethod": "SBI account / UPI",
      "person": null,
      "notes": ""
    },
    {
      "id": "t74",
      "date": "2026-08-20",
      "amount": 83,
      "source": "SBI",
      "dest": null,
      "type": "Expense",
      "category": "Food",
      "subcategory": "Eating out",
      "description": "Thrissur breakfast",
      "paymentMethod": "SBI account / UPI",
      "person": null,
      "notes": ""
    },
    {
      "id": "t75",
      "date": "2026-08-20",
      "amount": 113,
      "source": "SBI",
      "dest": null,
      "type": "Expense",
      "category": "Work Related",
      "subcategory": "Travel expense",
      "description": "Thrissur uber",
      "paymentMethod": "SBI account / UPI",
      "person": null,
      "notes": ""
    },
    {
      "id": "t76",
      "date": "2026-08-20",
      "amount": 55,
      "source": "SBI",
      "dest": null,
      "type": "Expense",
      "category": "Food",
      "subcategory": "Snacks",
      "description": "Water & drinks",
      "paymentMethod": "SBI account / UPI",
      "person": null,
      "notes": ""
    },
    {
      "id": "t77",
      "date": "2026-08-20",
      "amount": 140,
      "source": "SBI",
      "dest": null,
      "type": "Expense",
      "category": "Food",
      "subcategory": "Eating out",
      "description": "Lunch",
      "paymentMethod": "SBI account / UPI",
      "person": null,
      "notes": ""
    },
    {
      "id": "t78",
      "date": "2026-08-20",
      "amount": 62,
      "source": "SBI",
      "dest": null,
      "type": "Expense",
      "category": "Work Related",
      "subcategory": "Travel expense",
      "description": "Thrissur uber",
      "paymentMethod": "SBI account / UPI",
      "person": null,
      "notes": ""
    },
    {
      "id": "t79",
      "date": "2026-08-20",
      "amount": 110,
      "source": "SBI",
      "dest": null,
      "type": "Expense",
      "category": "Work Related",
      "subcategory": "Travel expense",
      "description": "Thrissur return",
      "paymentMethod": "SBI account / UPI",
      "person": null,
      "notes": ""
    },
    {
      "id": "t80",
      "date": "2026-08-20",
      "amount": 1000,
      "source": "IOB Salary",
      "dest": "SBI",
      "type": "Transfer",
      "category": null,
      "subcategory": null,
      "description": "Cash transfer",
      "paymentMethod": null,
      "person": null,
      "notes": ""
    },
    {
      "id": "t81",
      "date": "2026-08-20",
      "amount": 1060,
      "source": "SBI",
      "dest": null,
      "type": "Expense",
      "category": "Personal",
      "subcategory": "Clothing",
      "description": "Mundu for onam",
      "paymentMethod": "SBI account / UPI",
      "person": null,
      "notes": ""
    },
    {
      "id": "t82",
      "date": "2026-08-20",
      "amount": 75,
      "source": "SBI",
      "dest": null,
      "type": "Expense",
      "category": "Food",
      "subcategory": "Eating out",
      "description": "Water & biscuit",
      "paymentMethod": "SBI account / UPI",
      "person": null,
      "notes": ""
    },
    {
      "id": "t83",
      "date": "2026-08-20",
      "amount": 192,
      "source": "SBI",
      "dest": null,
      "type": "Expense",
      "category": "Food",
      "subcategory": "Eating out",
      "description": "Dinner",
      "paymentMethod": "SBI account / UPI",
      "person": null,
      "notes": ""
    },
    {
      "id": "t84",
      "date": "2026-08-21",
      "amount": 170,
      "source": "SBI",
      "dest": null,
      "type": "Expense",
      "category": "Family",
      "subcategory": "Family support",
      "description": "Haris expense",
      "paymentMethod": "SBI account / UPI",
      "person": null,
      "notes": ""
    },
    {
      "id": "t85",
      "date": "2026-08-22",
      "amount": 81,
      "source": "SBI",
      "dest": null,
      "type": "Expense",
      "category": "Family",
      "subcategory": "Family support",
      "description": "Anees expense",
      "paymentMethod": "SBI account / UPI",
      "person": null,
      "notes": ""
    },
    {
      "id": "t86",
      "date": "2026-08-22",
      "amount": 120,
      "source": "SBI",
      "dest": null,
      "type": "Expense",
      "category": "Vehicle",
      "subcategory": "Petrol/Fuel",
      "description": "Petrol",
      "paymentMethod": "SBI account / UPI",
      "person": null,
      "notes": ""
    },
    {
      "id": "t87",
      "date": "2026-08-22",
      "amount": 500,
      "source": "IOB Salary",
      "dest": "SBI",
      "type": "Transfer",
      "category": null,
      "subcategory": null,
      "description": "Cash transfer",
      "paymentMethod": null,
      "person": null,
      "notes": ""
    },
    {
      "id": "t88",
      "date": "2026-08-22",
      "amount": 120,
      "source": "SBI",
      "dest": null,
      "type": "Expense",
      "category": "Vehicle",
      "subcategory": "Petrol/Fuel",
      "description": "Petrol",
      "paymentMethod": "SBI account / UPI",
      "person": null,
      "notes": ""
    },
    {
      "id": "t89",
      "date": "2026-08-22",
      "amount": 120,
      "source": "SBI",
      "dest": null,
      "type": "Expense",
      "category": "Vehicle",
      "subcategory": "Petrol/Fuel",
      "description": "Petrol",
      "paymentMethod": "SBI account / UPI",
      "person": null,
      "notes": ""
    },
    {
      "id": "t90",
      "date": "2026-08-22",
      "amount": 500,
      "source": "IOB Salary",
      "dest": "SBI",
      "type": "Transfer",
      "category": null,
      "subcategory": null,
      "description": "Cash transfer",
      "paymentMethod": null,
      "person": null,
      "notes": ""
    },
    {
      "id": "t91",
      "date": "2026-08-22",
      "amount": 500,
      "source": "SBI",
      "dest": null,
      "type": "Expense",
      "category": "Work Related",
      "subcategory": "Pickup fuel",
      "description": "Tools shifting to NCC",
      "paymentMethod": "SBI account / UPI",
      "person": null,
      "notes": ""
    },
    {
      "id": "t92",
      "date": "2026-08-22",
      "amount": 24,
      "source": "SBI",
      "dest": null,
      "type": "Expense",
      "category": "Food",
      "subcategory": "Snacks",
      "description": "Tea",
      "paymentMethod": "SBI account / UPI",
      "person": null,
      "notes": ""
    },
    {
      "id": "t93",
      "date": "2026-08-23",
      "amount": 120,
      "source": "SBI",
      "dest": null,
      "type": "Expense",
      "category": "Vehicle",
      "subcategory": "Petrol/Fuel",
      "description": "Petrol(transferred to Haris)",
      "paymentMethod": "SBI account / UPI",
      "person": null,
      "notes": ""
    },
    {
      "id": "t94",
      "date": "2026-08-24",
      "amount": 110,
      "source": "SBI",
      "dest": null,
      "type": "Expense",
      "category": "Personal",
      "subcategory": "Entertainment",
      "description": "eFootball coin purchase",
      "paymentMethod": "SBI account / UPI",
      "person": null,
      "notes": ""
    },
    {
      "id": "t95",
      "date": "2026-08-24",
      "amount": 300,
      "source": "Physical Cash",
      "dest": null,
      "type": "Income",
      "category": "Family",
      "subcategory": "Family support",
      "description": "Received from mother",
      "paymentMethod": "Physical cash",
      "person": "Mother",
      "notes": ""
    },
    {
      "id": "t96",
      "date": "2026-08-24",
      "amount": 300,
      "source": "IOB Salary",
      "dest": "SBI",
      "type": "Transfer",
      "category": null,
      "subcategory": null,
      "description": "Cash transfer",
      "paymentMethod": null,
      "person": null,
      "notes": ""
    },
    {
      "id": "t97",
      "date": "2026-08-24",
      "amount": 2000,
      "source": "Physical Cash",
      "dest": null,
      "type": "Debt borrowed",
      "category": "Debt & Loans",
      "subcategory": "Debt borrowed by me",
      "description": "Lent borrowed from Shibina",
      "paymentMethod": "Physical cash",
      "person": null,
      "notes": ""
    },
    {
      "id": "t98",
      "date": "2026-08-24",
      "amount": 225,
      "source": "Physical Cash",
      "dest": null,
      "type": "Expense",
      "category": "Family",
      "subcategory": "Other family expense",
      "description": "Ponmudi tea",
      "paymentMethod": "Physical cash",
      "person": null,
      "notes": ""
    },
    {
      "id": "t99",
      "date": "2026-08-24",
      "amount": 50,
      "source": "Physical Cash",
      "dest": null,
      "type": "Expense",
      "category": "Housing & Household",
      "subcategory": "Groceries",
      "description": "Chappathi",
      "paymentMethod": null,
      "person": null,
      "notes": ""
    },
    {
      "id": "t100",
      "date": "2026-08-25",
      "amount": 300,
      "source": "Physical Cash",
      "dest": null,
      "type": "Expense",
      "category": "Family",
      "subcategory": "Family support",
      "description": "Haris expense",
      "paymentMethod": "Physical cash",
      "person": null,
      "notes": ""
    },
    {
      "id": "t101",
      "date": "2026-08-25",
      "amount": 1652,
      "source": "SBI",
      "dest": null,
      "type": "Refund/Reimbursement",
      "category": "Work Related",
      "subcategory": "Other work expeses",
      "description": "Blife petty cash return",
      "paymentMethod": null,
      "person": null,
      "notes": ""
    },
    {
      "id": "t102",
      "date": "2026-08-25",
      "amount": 200,
      "source": "Physical Cash",
      "dest": null,
      "type": "Expense",
      "category": "Family",
      "subcategory": "Family travel/transport",
      "description": "Umma eye hospital uber",
      "paymentMethod": "Physical cash",
      "person": null,
      "notes": ""
    },
    {
      "id": "t103",
      "date": "2026-08-25",
      "amount": 300,
      "source": "Physical Cash",
      "dest": null,
      "type": "Expense",
      "category": "Family",
      "subcategory": "Family medical",
      "description": "Umma eye hospital OP",
      "paymentMethod": "Physical cash",
      "person": null,
      "notes": ""
    },
    {
      "id": "t104",
      "date": "2026-08-25",
      "amount": 350,
      "source": "Physical Cash",
      "dest": null,
      "type": "Expense",
      "category": "Family",
      "subcategory": "Family medical",
      "description": "Umma eye hospital medicine",
      "paymentMethod": "Physical cash",
      "person": null,
      "notes": ""
    },
    {
      "id": "t105",
      "date": "2026-08-25",
      "amount": 130,
      "source": "Physical Cash",
      "dest": null,
      "type": "Expense",
      "category": "Family",
      "subcategory": "Family travel/transport",
      "description": "Umma hospital to home uber",
      "paymentMethod": "Physical cash",
      "person": null,
      "notes": ""
    }
  ],
  "budget": [
    {
      "category": "Food",
      "importance": "Discretionary",
      "monthlyBudget": null
    },
    {
      "category": "Housing & Household",
      "importance": "Essential",
      "monthlyBudget": null
    },
    {
      "category": "Vehicle",
      "importance": "Important",
      "monthlyBudget": null
    },
    {
      "category": "Family",
      "importance": "Important",
      "monthlyBudget": null
    },
    {
      "category": "Personal",
      "importance": "Discretionary",
      "monthlyBudget": null
    },
    {
      "category": "Entertainment",
      "importance": "Discretionary",
      "monthlyBudget": null
    },
    {
      "category": "Work Related",
      "importance": "Essential",
      "monthlyBudget": null
    },
    {
      "category": "Other",
      "importance": "Discretionary",
      "monthlyBudget": null
    }
  ],
  "debts": [
    {
      "id": "d1",
      "name": "Slice — Laptop",
      "balance": 64285.85,
      "dueDay": 5,
      "interestRate": null,
      "notes": ""
    },
    {
      "id": "d2",
      "name": "KreditBee",
      "balance": 12570,
      "dueDay": 8,
      "interestRate": null,
      "notes": ""
    },
    {
      "id": "d3",
      "name": "Household Shop Credit",
      "balance": null,
      "dueDay": null,
      "interestRate": null,
      "notes": ""
    }
  ],
  "friendFamily": [
    {
      "id": "f1",
      "person": "Anees",
      "direction": "I Lent",
      "date": "2026-08-16",
      "amount": 6500,
      "reason": "Money lent",
      "amountSettled": 0,
      "settlementDate": null,
      "notes": "To be returned by brother"
    },
    {
      "id": "f2",
      "person": "Haris",
      "direction": "I Lent",
      "date": "2026-08-16",
      "amount": 1000,
      "reason": "Money lent",
      "amountSettled": 0,
      "settlementDate": null,
      "notes": "No expected return date tracked"
    },
    {
      "id": "f3",
      "person": "Shibina",
      "direction": "Borrowed from",
      "date": "2026-08-24",
      "amount": 2000,
      "reason": "For Ponmudi family trip",
      "amountSettled": 0,
      "settlementDate": null,
      "notes": ""
    }
  ],
  "recurring": [
    {
      "id": "r1",
      "item": "Rent",
      "category": "Housing & Household",
      "expectedAmount": 8000,
      "dueDay": 15,
      "priority": "1 - Essential living",
      "notes": "Fixed",
      "account": "SBI account / UPI"
    },
    {
      "id": "r2",
      "item": "Electricity",
      "category": "Housing & Household",
      "expectedAmount": null,
      "dueDay": null,
      "priority": "1 - Essential living",
      "notes": "Normal range ₹1,500–₹2,500",
      "account": "Usually SBI / update"
    },
    {
      "id": "r3",
      "item": "Water",
      "category": "Housing & Household",
      "expectedAmount": null,
      "dueDay": null,
      "priority": "1 - Essential living",
      "notes": "Normal range ₹500–₹1,000",
      "account": "Usually SBI / update"
    },
    {
      "id": "r4",
      "item": "Slice",
      "category": "Debt & Loans",
      "expectedAmount": 5806.89,
      "dueDay": 5,
      "priority": "2 - Debt/EMIs",
      "notes": "Payment 1",
      "account": "SBI account / UPI"
    },
    {
      "id": "r5",
      "item": "KreditBee",
      "category": "Debt & Loans",
      "expectedAmount": 1571,
      "dueDay": 8,
      "priority": "2 - Debt/EMIs",
      "notes": "Payment 1",
      "account": "SBI account / UPI"
    },
    {
      "id": "r6",
      "item": "Chit",
      "category": "Financial",
      "expectedAmount": 3333,
      "dueDay": 15,
      "priority": "3 - Chit",
      "notes": "Contribution 1 — around salary date",
      "account": "SBI account / UPI"
    }
  ],
  "investments": [
    {
      "id": "i1",
      "name": "Kotak Gold",
      "type": "Mutual Fund",
      "purchaseDate": null,
      "originalInvested": 1705,
      "additional": 0,
      "withdrawals": 0,
      "currentValue": 1951,
      "notes": "Active — approximate age supplied; purchase date not provided."
    },
    {
      "id": "i2",
      "name": "Old Mutual Fund — Details TBD",
      "type": "Mutual Fund",
      "purchaseDate": null,
      "originalInvested": null,
      "additional": 0,
      "withdrawals": 0,
      "currentValue": null,
      "notes": "Details TBD — do not invent values."
    }
  ],
  "chit": {
    "members": 9,
    "contribution": 3333,
    "payout": 30000,
    "contributionsRemaining": 7,
    "payoutStatus": "Pending"
  },
  "pettyCash": {
    "opening": 0,
    "openingDate": "2026-08-10"
  },
  "settings": {
    "categorySubcategoryMap": {
      "Housing & Household": [
        "Rent",
        "Groceries",
        "Household items",
        "Electricity",
        "Water",
        "Internet/phone",
        "Home maintenance",
        "Other household"
      ],
      "Food": [
        "Eating out",
        "Snacks",
        "Food delivery",
        "Other food"
      ],
      "Debt & Loans": [
        "Slice — Laptop",
        "KreditBee",
        "Debt borrowed by me",
        "Debt repaid by me",
        "Debt borrowed from me",
        "Debt repaid to me",
        "Shop credit repayment",
        "Other debt repayment"
      ],
      "Vehicle": [
        "Petrol/Fuel",
        "Maintenance",
        "Repairs",
        "Insurance",
        "Road tax",
        "Penalties/Fines",
        "Accessories",
        "Other vehicle expense"
      ],
      "Family": [
        "Family support",
        "Family medical",
        "Family travel/transport",
        "Family gifts/occasions",
        "Other family expense",
        "Clothing"
      ],
      "Personal": [
        "Personal care",
        "Shopping",
        "Entertainment",
        "Subscriptions",
        "Other personal",
        "Emergency fund"
      ],
      "Financial": [
        "Investment",
        "Chit contribution",
        "Bank charges",
        "Other financial expense",
        "Uncategorized"
      ],
      "Other": [
        "Other",
        "Pickup fuel"
      ],
      "Work Related": [
        "Travel expense",
        "Tools/equipments",
        "Worker's food",
        "Accomodation",
        "Parcel charges",
        "Services",
        "Other work expeses"
      ]
    },
    "paymentMethods": [
      "SBI account / UPI",
      "IOB Salary account / UPI",
      "IOB Personal account / UPI",
      "Physical cash",
      "Debit card",
      "ATM cash withdrawal"
    ],
    "transactionTypes": [
      "Income",
      "Expense",
      "Transfer",
      "Debt borrowed",
      "Debt repayment",
      "Loan EMI",
      "Savings",
      "Investment",
      "Refund/Reimbursement",
      "Adjustment",
      "Money Lent",
      "Money Received - Lent",
      "Chit payout"
    ],
    "importanceLevels": [
      "Essential",
      "Important",
      "Discretionary"
    ],
    "people": [
      "Brother",
      "Brother 2",
      "Employer",
      "Friend 1",
      "Friend 2",
      "Mother",
      "Haris",
      "Anees",
      "Shibina"
    ],
    "investmentTypes": [
      "Mutual Fund",
      "Gold/Commodity",
      "Stocks",
      "ETF",
      "Other"
    ]
  }
};
